// Code generated by goctl. DO NOT EDIT.
package types

type SignupRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender,options=male|female|secret,default=secret"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
