// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	ReviewAppealInfo *reviewAppealInfo
	ReviewInfo       *reviewInfo
	ReviewReplyInfo  *reviewReplyInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ReviewAppealInfo = &Q.ReviewAppealInfo
	ReviewInfo = &Q.ReviewInfo
	ReviewReplyInfo = &Q.ReviewReplyInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		ReviewAppealInfo: newReviewAppealInfo(db, opts...),
		ReviewInfo:       newReviewInfo(db, opts...),
		ReviewReplyInfo:  newReviewReplyInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ReviewAppealInfo reviewAppealInfo
	ReviewInfo       reviewInfo
	ReviewReplyInfo  reviewReplyInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		ReviewAppealInfo: q.ReviewAppealInfo.clone(db),
		ReviewInfo:       q.ReviewInfo.clone(db),
		ReviewReplyInfo:  q.ReviewReplyInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		ReviewAppealInfo: q.ReviewAppealInfo.replaceDB(db),
		ReviewInfo:       q.ReviewInfo.replaceDB(db),
		ReviewReplyInfo:  q.ReviewReplyInfo.replaceDB(db),
	}
}

type queryCtx struct {
	ReviewAppealInfo IReviewAppealInfoDo
	ReviewInfo       IReviewInfoDo
	ReviewReplyInfo  IReviewReplyInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ReviewAppealInfo: q.ReviewAppealInfo.WithContext(ctx),
		ReviewInfo:       q.ReviewInfo.WithContext(ctx),
		ReviewReplyInfo:  q.ReviewReplyInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
