// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Title       string    `gorm:"column:title;not null;comment:书籍名称" json:"title"`              // 书籍名称
	Author      string    `gorm:"column:author;not null;comment:作者" json:"author"`              // 作者
	Price       int32     `gorm:"column:price;not null;comment:价格" json:"price"`                // 价格
	PublishDate time.Time `gorm:"column:publish_date;comment:出版日期" json:"publish_date"`         // 出版日期
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
