server:
  http:
    addr: 0.0.0.0:${HTTP_PORT:8000}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    dsn: root:root1234@tcp(127.0.0.1:3306)/db3
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
mode: dev