server:
  http:
    addr: 0.0.0.0:8484
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9494
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http